set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g status-style bg="#1914b9"
# set -as terminal-features ",*:RGB"
# set -ag terminal-overrides ",alacritty:RGB"
set -g mouse on 
